from __future__ import annotations

import os

import torch
from sklearn.cluster import AgglomerativeClustering

from .compat import torch_safe_globals_ctx

_vad_model = None
_vad_utils = None
_spk_encoder = None


def _load_vad_cpu():
    global _vad_model, _vad_utils
    if _vad_model is None or _vad_utils is None:
        with torch_safe_globals_ctx():
            _vad_model, _vad_utils = torch.hub.load(
                repo_or_dir="snakers4/silero-vad",
                model="silero_vad",
                trust_repo=True,
            )
        try:
            _vad_model.to(torch.device("cpu"))
        except Exception:
            pass
    return _vad_model, _vad_utils


def _load_spk_encoder(device: str):
    global _spk_encoder
    if _spk_encoder is None:
        with torch_safe_globals_ctx():
            from speechbrain.inference.speaker import EncoderClassifier

            source = os.environ.get("SPK_EMB_MODEL", "speechbrain/spkrec-ecapa-voxceleb")
            try:
                _spk_encoder = EncoderClassifier.from_hparams(
                    source=source,
                    run_opts={"device": device},
                )
            except Exception as e:
                # SpeechBrain иногда пытается скачать custom.py, которого нет в репозитории модели,
                # и падает 404. Обходим: скачиваем репо локально и создаём пустой custom.py.
                msg = str(e)
                if "custom.py" not in msg and "Entry Not Found" not in msg and "404" not in msg:
                    raise

                from huggingface_hub import snapshot_download

                local_dir = os.path.join(
                    os.path.dirname(__file__),
                    "..",
                    ".hf_cache",
                    source.replace("/", "__"),
                )
                local_dir = os.path.abspath(local_dir)
                os.makedirs(local_dir, exist_ok=True)

                snapshot_download(
                    repo_id=source,
                    local_dir=local_dir,
                    local_dir_use_symlinks=False,
                )
                custom_py = os.path.join(local_dir, "custom.py")
                if not os.path.exists(custom_py):
                    with open(custom_py, "w", encoding="utf-8") as f:
                        f.write("# autogenerated to satisfy SpeechBrain loader\n")

                _spk_encoder = EncoderClassifier.from_hparams(
                    source=local_dir,
                    savedir=local_dir,
                    run_opts={"device": device},
                )
    return _spk_encoder


def diarize(wav_path: str, device: str) -> list[tuple[float, float, str]]:
    """
    Diarization без gated моделей:
    Silero VAD -> ECAPA embeddings -> agglomerative clustering.

    Returns list of turns (start_sec, end_sec, speaker_label).
    """
    import numpy as np
    import soundfile as sf

    vad_model, vad_utils = _load_vad_cpu()
    get_speech_timestamps = vad_utils[0]
    read_audio = vad_utils[2]

    wav = read_audio(wav_path, sampling_rate=16000)
    timestamps = get_speech_timestamps(
        wav,
        vad_model,
        sampling_rate=16000,
        min_speech_duration_ms=int(os.environ.get("VAD_MIN_SPEECH_MS", "250")),
        min_silence_duration_ms=int(os.environ.get("VAD_MIN_SILENCE_MS", "120")),
        threshold=float(os.environ.get("VAD_THRESHOLD", "0.5")),
    )
    if not timestamps:
        return []

    turns = []
    gap = float(os.environ.get("VAD_MERGE_GAP_SEC", "0.25"))
    for ts in timestamps:
        s = float(ts["start"]) / 16000.0
        e = float(ts["end"]) / 16000.0
        if not turns:
            turns.append([s, e])
        else:
            if s - turns[-1][1] <= gap:
                turns[-1][1] = max(turns[-1][1], e)
            else:
                turns.append([s, e])

    audio, sr = sf.read(wav_path, dtype="float32", always_2d=False)
    if sr != 16000:
        raise RuntimeError(f"Expected 16000 Hz, got {sr}")
    if getattr(audio, "ndim", 1) > 1:
        audio = np.mean(audio, axis=1)

    encoder = _load_spk_encoder(device=device)
    min_chunk = float(os.environ.get("SPK_MIN_CHUNK_SEC", "1.0"))
    emb_list = []
    used_turns = []
    for s, e in turns:
        dur = e - s
        if dur <= 0.05:
            continue
        pad_e = max(e, s + min_chunk)
        i0 = int(max(0.0, s) * sr)
        i1 = int(min(len(audio), pad_e * sr))
        chunk = audio[i0:i1]
        if len(chunk) < int(min_chunk * sr):
            chunk = np.pad(chunk, (0, int(min_chunk * sr) - len(chunk)))
        wav_tensor = torch.from_numpy(chunk).unsqueeze(0).to(torch.device(device))
        with torch.no_grad():
            emb_t = encoder.encode_batch(wav_tensor)
            emb = emb_t.detach().cpu().numpy().reshape(-1)
        emb_list.append(emb)
        used_turns.append((s, e))

    if not emb_list:
        return []

    X = np.stack(emb_list, axis=0)
    if X.shape[0] == 1:
        s, e = used_turns[0]
        return [(s, e, "SPEAKER_00")]

    dist = float(os.environ.get("SPK_CLUSTER_THRESHOLD", "0.7"))
    clustering = AgglomerativeClustering(
        n_clusters=None,
        metric="cosine",
        linkage="average",
        distance_threshold=dist,
    )
    labels = clustering.fit_predict(X)

    labeled = [(s, e, f"SPEAKER_{int(lab):02d}") for (s, e), lab in zip(used_turns, labels)]

    out = []
    merge_gap = float(os.environ.get("SPK_MERGE_GAP_SEC", "0.4"))
    for s, e, spk in labeled:
        if not out:
            out.append([s, e, spk])
        else:
            ps, pe, pspk = out[-1]
            if spk == pspk and s - pe <= merge_gap:
                out[-1][1] = max(pe, e)
            else:
                out.append([s, e, spk])

    return [(a, b, c) for a, b, c in out]


def reset_cache() -> None:
    global _vad_model, _vad_utils, _spk_encoder
    _vad_model = None
    _vad_utils = None
    _spk_encoder = None

